### ISSUE TITLE
Feature: add $session_id to Web Pixel extension to support event processing in PostHog Web Analytics

### ISSUE THREAD

**Issue by OmG3r** [celadonworks/pixiehog-app#9]
## Introduction
Currently the Web Pixel uses [posthog-js-lite/posthog-node](https://github.com/PostHog/posthog-js-lite/tree/main/posthog-node) instead of [posthog-js](https://github.com/PostHog/posthog-js) due to limitations in the Shopify Web Pixel environment.

`posthog-js` natively sends $session_id property with each event in order to group the events for Web analytics as stated in [PostHog -> Data -> Session documentation](https://posthog.com/docs/data/sessions).

as the Web Pixel Channel runs in a browser environment it is expected by users to simulate the behavior of `posthog-js`.

## Improvements
Scenario 1: JS Web channel is enabled and will manage $session_id state (saved into localStorage) - this will ensure that events from both channels are properly linked.
1. Retrieve `$session_id` if it is specified by JS Web channel (`posthog-js`)
2. Add `$session_id` to all Web Pixel channel events.

Scenario 2: JS Web channel is not enabled - Web Pixel channel needs to manually manage `$session_id` variable
1. Determine that `$session_id` is not provided in localStorage (No JS Web Channel enabled)
2. Generate a random `uuidv7` to act as `session_id` and save it into localStorage with current timestamp
3. Add `$session_id` to all Web Pixel channel events.
4. On Web Pixel channel load - set last_activity to current date to calculate 30 min duration before starting a new `$session_id`
## Resources
[Posthog -> Resources -> Data -> Sessions -> Session Properties](https://posthog.com/docs/data/sessions#session-properties)

**Comment by BrandonJamesBorders** [comment]
@ahmedbm27 When do you think this feature will be live?

**Comment by ahmedbm27** [comment]
@BrandonJamesBorders it’s live now! We just pushed the feature, so you should be good to go. Let us know if anything’s off

**Comment by BrandonJamesBorders** [comment]
I am starting to see it in some places now. It is still missing in the checkout_completed event, as well as all others, where the library is posthog-node. 

Anything I need to do to get that working? 

![Image](https://github.com/user-attachments/assets/8b5ed28a-1027-48aa-a7a0-60e526fd6945)
![Image](https://github.com/user-attachments/assets/ad472610-5315-4294-b4a7-bf05af513f05)

**Comment by OmG3r** [comment]
Hey @BrandonJamesBorders ,
would you please check again if the session_id now appears properly ? I have made few changes to the extension.
